doc/urls.py
from django.conf.urls import url, include
from .api import TemplateList, TemplateDetail
from .api import BotList, BotDetail, AdminBotList
from .views import bots_index


app_name="registration.api"

template_api_urls = [
    url(r'^(?P<name>[0-9a-zA-Z_-]+)$', TemplateDetail.as_view(), name='template-detail'),
    url(r'^$', TemplateList.as_view(), name='template-list')
]

bot_api_urls = [

    url(r'^(?P<pk>\d+)$', BotDetail.as_view(), name='bot-detail'),
    url(r'^$', BotList.as_view(), name='bot-list'),
    url(r'^(?P<username>[0-9a-zA-Z_-]+)$', AdminBotList.as_view(), name='adminbot-list')
]


urlpatterns = [
    url(r'^api/templates/', include(template_api_urls)),
    url(r'^api/bots/', include(bot_api_urls)),
    url(r'^$', bots_index, name='bots-registration')
]

userprofiles/urls.py
from django.conf.urls import url
from userprofiles.views import ProfileHomeView, ProfileIdentite

app_name = "profile"
urlpatterns = [
    url(r'^$', ProfileHomeView.as_view(), name='home'),
    url(r'^identity/(?P<pk>[0-9]+)/$', ProfileIdentite.as_view(), name='identity-form'),
]

userprofiles/models.py
from django.db import models
from botmint.users.models import User
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

GENDER =(('man','Man'),('woman','Woman'))

""" userprofile class to add users"""
class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, related_name="profile", verbose_name=_(u'User'), on_delete=models.CASCADE)
    phone = PhoneNumberField(null=True, blank=True)
    gender = models.CharField(max_length=40, blank=True, verbose_name=_(u'Gender'), choices=GENDER)
    avatar = models.ImageField(upload_to='userprofiles/avatars', null=True, blank=True, verbose_name=_(u"Avatar"))
    completion_level = models.PositiveSmallIntegerField(default=0, verbose_name=_(u'Profile completion percentage'))
    email_is_verified = models.BooleanField(default=False, verbose_name=_(u'Email is verified'))
    personal_info_is_completed = models.BooleanField(default=False, verbose_name=_(u'Personal info completed'))

    class Meta:
        verbose_name=_(u'User profile')
        verbose_name_plural = _(u'User profiles')

    def __unicode__(self):
        return u"User profile: %s" % self.user.username

    def get_completion_level(self):
        completion_level = 0
        if self.email_is_verified:
            completion_level += 50
        if self.personal_info_is_completed:
            completion_level += 50
        return completion_level

    """ update the user info completion level"""
    def update_completion_level(self):
        self.completion_level = self.get_completion_level()
        self.save()
        return

userprofiles/forms.py
from django import forms
from django.http import Http404
from django.contrib.auth.models import User
from userprofiles.models import UserProfile


class IdentiteForm(forms.ModelForm):
    first_name = forms.CharField(max_length=256)
    last_name = forms.CharField(max_length=256)


    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name','gender','phone',)
        widgets = {'phone': forms.TextInput()}
        help_texts = {
            'phone': 'Please enter phone no in +(country code)(contact number)',
        }

    def __init__(self, *args, **kwargs):
        super(IdentiteForm, self).__init__(*args, **kwargs)
        try:
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['last_name'].initial = self.instance.user.last_name
        except User.DoesNotExist:
            raise Http404
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['gender'].required = True
        self.fields['phone'].required = True
        return


class EmailForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email']

    def __init__(self, *args, **kwargs):
        super(EmailForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

userprofiles/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic.edit import UpdateView
from django.views.generic import TemplateView
from allauth.account.utils import send_email_confirmation
from braces.views import LoginRequiredMixin
from userprofiles.models import UserProfile
from userprofiles.forms import IdentiteForm, EmailForm


class ProfileHomeView(LoginRequiredMixin, TemplateView):
    template_name = 'userprofiles/home.html'
    user_check_failure_path = '/comptes/signup/'

    def check_user(self, user):
        if user.is_active:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super(ProfileHomeView, self).get_context_data(**kwargs)
        profile = UserProfile.objects.get_or_create(user=self.request.user)[0]
        context['profile'] = profile
        return context


class ProfileIdentite(LoginRequiredMixin, UpdateView):
    template_name = "userprofiles/identity_form.html"
    form_class = IdentiteForm
    user_check_failure_path = '/comptes/login/'
    success_url = reverse_lazy("profile:home")

    def get_queryset(self):
        queryset = UserProfile.objects.filter(user=self.request.user)
        return queryset

    def form_valid(self, form, **kwargs):
        profile = form.save(commit=False)
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()
        profile.gender = form.cleaned_data['gender']
        profile.phone = form.cleaned_data['phone']
        profile.personal_info_is_completed = True
        profile.completion_level = profile.get_completion_level()
        profile.save()
        #return super(ProfileIdentite, self).form_valid(form)
        return HttpResponseRedirect(self.get_success_url())

userprofiles/templates/userprofiles/email_form.html
{% extends "base.html" %}
{% load staticfiles bootstrap %}

{% block title %}Mon compte > Email{% endblock %}

{% block content %}
<div class="row">
	<div class="col-xs-12 col-md-offset-1 col-md-10 col-md-offset-1 col-lg-offset-2 col-lg-8 col-lg-offset-2">
		<h1>Email</h1>
		<form action="" method="post">{% csrf_token %}
		    {{ form|bootstrap }}
		    {% if user.profile.email_is_verified %}
		    	<input type="submit" class="btn btn-primary" value="Changer et revérifier l'email" />
		    {% else %}
		    	<input type="submit" class="btn btn-primary" value="Vérifier l'email" />
		    {% endif %}
		</form>
	</div>
</div>

{% endblock %}

userprofiles/templates/userprofiles/home.html
{% extends "base.html" %}
{% load i18n avatar_tags %}

{% block title %}{% trans "My profile" %}{% endblock %}

{% block content %}
<style>
.grey {
	color:grey;
}
.success {
	color:green;
}
</style>
<div class="row">
	<div class="col-xs-12 col-md-offset-1 col-md-10 col-md-offset-1 col-lg-offset-2 col-lg-8 col-lg-offset-2">
		<div style="float:left;margin:1em 1em 0 0">
			<a href="{% url 'avatar_change' %}">
				{% avatar user 50 class="img-circle img-responsive" style="vertical-align:center" id="user_avatar" %}
			</a>
		</div>
		<h1>{{ user.username }}</h1>
		<p>{% if profile.completion_level == 100 %}<i class="fa fa-user fa-lg success"></i>&nbsp;{% endif %}{% trans "Profile completed at" %}
			<span class="generic_bold">
				{{ profile.completion_level }}%
			</span>
		</p>
	    <div class="progress">
	        <div class="progress-bar progress-bar-success" style="width:{{ profile.completion_level }}%;">
	            {{ profile.completion_level }}%
	        </div>
	    </div>
		{% if not profile.completion_level == 100 %}
			<p class="alert alert-info text-center">
				<i class="fa fa-user-times fa-lg"></i>&nbsp;{% trans "Your profile must be completed in order to access all the features of the site" %}
			</p>
			<h3 class="text-center" style="margin-bottom:1.5em">{% trans "Thank you to complete these informations:" %}</h3>
		{% endif %}
		<div class="row">
			<div class="col-sm-6">
			    <div class="panel panel-default">
			        <div class="panel-heading">
			        	<div class="pull-right">
				        	{% if not profile.email_is_verified %}
				        		<a href="{% url 'account_email' %}">
				        			<i class="fa fa-close fa-2x pull-right text-danger"></i>
				        		</a>
				        	{% else %}
				        		<i class="fa fa-check fa-2x success"></i>
				        	{% endif %}
				        </div>
				        <h4><i class="fa fa-envelope-o fa-lg"></i>&nbsp;{% trans "Email adress verification" %}</h4>
			        </div>
			        <div class="panel-body">
			        	{% if not profile.email_is_verified %}
								<a href="{% url 'account_email' %}" class="btn btn-primary">{% trans "Verify email" %}</a>
							{% else %}
								<a href="{% url 'account_email' %}" class="btn btn-default">{% trans "Edit email" %}</a>
						{% endif %}
			        </div>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="panel panel-default">
			        <div class="panel-heading">
			        	<div class="pull-right">
				        	{% if not profile.personal_info_is_completed %}
				        		<a href="{% url "profile:identity-form" profile.pk %}">
				        			<i class="fa fa-close fa-2x pull-right grey"></i>
				        		</a>
				        	{% else %}
				        		<i class="fa fa-check fa-2x text-success"></i>
				        	{% endif %}
				        </div>
				        <h4><i class="fa fa-book fa-lg"></i>&nbsp;{% trans "Personal infos" %}</h4>
			        </div>
			        <div class="panel-body">
						{% if profile.personal_info_is_completed %}
							<a href="{% url "profile:identity-form" profile.pk %}" class="btn btn-default">{% trans "Edit" %}</a>
						{% else %}
							<a href="{% url "profile:identity-form" profile.pk %}" class="btn btn-primary">{% trans "Complete now" %}</a>
						{% endif %}
			        </div>
			    </div>
		    </div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<p class="gc gus-l">
					<a href="{% url 'avatar_change' %}" class="btn btn-link">{% trans "Change your avatar" %}</a>
					<a href="{% url 'account_change_password' %}" class="btn btn-link">{% trans "Change your password" %}</a>
				</p>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

userprofiles/templates/userprofiles/identity_form.html
{% extends "base.html" %}
{% load i18n staticfiles bootstrap avatar_tags %}

{% block title %}{% trans "My profile: Identity" %}{% endblock %}

{% block content %}
<div class="row">
	<div class="col-xs-12 col-md-offset-1 col-md-10 col-md-offset-1 col-lg-offset-2 col-lg-8 col-lg-offset-2">
		<div style="float:left;margin:1em 1em 0 0">
			<a href="{% url 'avatar_change' %}">
				{% avatar user 50 class="img-circle img-responsive" style="vertical-align:center" id="user_avatar" %}
			</a>
		</div>
		<h1>{{ user.username }} : {% trans "Identity" %}</h1>
		<form action="" class="form-horizontal" method="post">{% csrf_token %}
		    {{ form|bootstrap }}
		    <div style="margin-top:2.5em">
		    	<input type="submit" class="btn btn-primary btn-lg pull-right" value="{% trans "Save" %}" />
		    	<a href="javascript:history.back()" class="btn btn-lg btn-default">{% trans "Back" %}</a>
			</div>
		</form>
	</div>
</div>
{% endblock %}

userprofiles/templates/userprofiles/personal_infos_form.html
{% extends "base.html" %}
{% load staticfiles bootstrap %}

{% block title %}Mon compte > Informations personelles{% endblock %}

{% block content %}
<div class="row">
	<div class="col-xs-12 col-md-offset-1 col-md-10 col-md-offset-1 col-lg-offset-2 col-lg-8 col-lg-offset-2">
		<h1>Informations personelles</h1>
		<form action="" class="form-horizontal" method="post">{% csrf_token %}
		    {{ form|bootstrap }}
		    <div>
		    	<input type="submit" class="btn btn-primary btn-lg pull-right" value="Envoyer" />
		    	<a href="javascript:history.back()" class="btn btn-default">Retour</a>
			</div>
		</form>
	</div>
</div>

{% endblock %}